-- Phase 1 schema (no ML yet)
-- Notes:
-- - UUIDs are generated by the application (Hibernate @UuidGenerator), not the DB.
-- - We keep enum-like columns as VARCHAR with CHECK constraints for portability.

create table if not exists public.users (
    id uuid primary key,
    name varchar(100) not null,
    email varchar(150) not null,
    password varchar(200) not null,
    role varchar(20) not null,
    constraint uk_users_email unique (email),
    constraint ck_users_role check (role in ('ADMIN', 'STUDENT'))
);

create table if not exists public.students (
    id uuid primary key,
    user_id uuid not null,
    roll_number varchar(50) not null,
    image_url text,
    constraint fk_students_user foreign key (user_id) references public.users(id) on delete cascade,
    constraint uk_students_user unique (user_id),
    constraint uk_students_roll unique (roll_number)
);

create table if not exists public.attendance (
    id uuid primary key,
    student_id uuid not null,
    date date not null,
    status varchar(20) not null,
    constraint fk_attendance_student foreign key (student_id) references public.students(id) on delete cascade,
    constraint ck_attendance_status check (status in ('PRESENT', 'ABSENT')),
    constraint uk_attendance_student_date unique (student_id, date)
);

create index if not exists idx_attendance_date on public.attendance(date);
create index if not exists idx_attendance_student on public.attendance(student_id);

